### ISSUE TITLE
MeasurementsController from and to are broken

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#24]
`MeasurementsController#reference_time` is used to calculate `from` and `to` values for fetching measurement readings from 15 minutes interval (so `from` and `to` should be set into values `[0,15]`, `[15,30]` and so on). Right now `from` and `to` uses `Time.now`. As a conclusion cached results are not deterministic.

**Comment by Nuanda** [comment]
That's why I use interval_number method to convert any time to those intervals. Can you explain in more detail what is the problem here?

**Comment by mkasztelnik** [comment]
[`to` method](https://github.com/Nuanda/smogmapper/blob/master/app/controllers/measurements_controller.rb#L37) is based on `reference_time` which don't necessary right now will be a quantity of 15 minutes. As a conclusion it has influence for the results returned by the sql query. The fix proposed [here](https://github.com/Nuanda/smogmapper/commit/1e2f72ef33a882d9134bb0b3d50c445fb5bfb20d) normalizes `reference_time` into quantity of 15 which solves this issue.

**Comment by mkasztelnik** [comment]
What is more in the fix I removed `minutes` from interval function because there is a problem with time multiplication (e.g. `2 * 15.minutes = 1800` - it is just an integer, no seconds object).

**Comment by Nuanda** [comment]
Correct.
