### ISSUE TITLE
Charts - better x and y axes ticks (if possible?)

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#3]

**Comment by mkasztelnik** [comment]
Can you elaborate more about this issue?

**Comment by Nuanda** [comment]
If you're able to save some vertical space (e.g. by removing the series labels below each charts - see another issue) you may try to make the charts higher. That might help with y axis ticks - currently they are sparse (like, only two or even one).

Regarding the x axis, the labels should be corrected, and more than two (i.e. the first and the latest) should be present. Since all three charts are aligned, you might even try to remove N-1 x axis labels, only making sure the last one is present.

**Comment by Nuanda** [comment]
Superseded by #49
