### ISSUE TITLE
Wrong procfile configuration

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#30]
https://github.com/Nuanda/smogmapper/blob/master/Procfile states that unicorn should be used to start the applicaiton (also unicorn configuraiton exists in config dir). It is not true according to `Gemfile` where only puma is defined in production environment (puma will be the default server in RoR 5.0 because of action cable). 

What is the official server for smogmapper?

**Comment by Nuanda** [comment]
It's puma.
