### ISSUE TITLE
Wrong data in current heatmap view

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#36]
It seems like current heatmap view is whole red. It should be very similar to iteration 0.

**Comment by Nuanda** [comment]
The controller returns twice as many readings for the 'Current heatmap' scenario. Probably the heatmap js plugin shows it the way it is - by superimposing colors.

**Comment by Nuanda** [comment]
Making the interval for the query 1 min shorter "solves" the problem:  where('time > ? AND time <= ?', to - (interval - 1).minutes, to)

**Comment by mkasztelnik** [comment]
Do you think we should go this way? It seems very tricky. Tomorrow I will check overhead for processing the data and leaving most recent one - @nowakowski something similar is in "last" DAP query, do you think this technique can be used here?

**Comment by Nuanda** [comment]
The "1 minute less" trick is kind of ok in "current situation" scenario. But I wonder if it's ok for animation scenario, where we don't want to miss things by accident.

**Comment by nowakowski** [comment]
Well, if you want the most recent reading for each sensor, then technically you should do something like this (and that's how DAP does it):
- Reverse order by sensor ID and internally by timestamp (`ORDER BY sensor_id, timestamp DESC`)
- Select first reading (`LIMIT 1`) for each sensor_id

Let me know if this solves your problem; I need to leave for about 4 hrs but will be back later today and will deal with pending tickets.

**Comment by mkasztelnik** [comment]
Reasigning into @nowakowski since the work he will do in the scope of #34 should solve this issue

**Comment by nowakowski** [comment]
The query in #34 should now return strictly 1 value per set of coordinates but there appear to be some serialization issues (see failing specs) which prevent me from being able to verify that this issue has been fixed. @Nuanda - could you run a check using the current version of the `token_and_locations` branch?

**Comment by Nuanda** [comment]
It's corrected now in PR #40 - please move all further development to #40. If you still have sth to push to #34, please do, and merge it with #40 afterwards.
