### ISSUE TITLE
Remove updated_at from measurements?

### ISSUE THREAD

**Issue by nowakowski** [Nuanda/smogmapper#47]
Seems like the `measurements` table may become crowded - in the interest of conserving storage space (and optimizing queries) I suggest ditching the `updated_at` timestamp and keeping only `created_at`.

**Comment by Nuanda** [comment]
Perhaps you mean the Readings table? Already removed timestamps there.

**Comment by nowakowski** [comment]
Right. My suggestion was based on an incorrect interpretation of the purpose of the `measurements` table. Closing issue.
