### ISSUE TITLE
Charts - move charts to big overlay dialog

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#49]
Leave the sidebar for general information, heatmap (and other) buttons and registration. Move charts to big, central dialog that could be dismissed with an 'x' button or similar. This should work for all screens in both orientation pretty good.

**Comment by Nuanda** [comment]
@mkasztelnik Marek, would you be willing to do that?

**Comment by mkasztelnik** [comment]
I can try to do this. What do you think about one chart with 3 series on it (off course use can turn on/off concrete series)? This would be much more userfriendly on mobile IMHO.

**Comment by Nuanda** [comment]
Remember those have different y axis scale. I was thinking about that but then I'm not sure three different y scales would not confuse the user. But we may try that (as long as highcharts is able to show three different y axes in proper fashion on a single chart).

**Comment by mkasztelnik** [comment]
It is possible to have multiple Y axis. Take a look at ISMOP UI for examples.

**Comment by Nuanda** [comment]
![ismop-chart](https://cloud.githubusercontent.com/assets/107565/12293946/279aa3fc-b9f7-11e5-8f8e-ac01c46aa3ef.png)

This is the overlay I mean. A nice extra thing would be to color-code also the y axes, if possible (to match series colors).

**Comment by Nuanda** [comment]
Since we are going to support also more sophisticated devices with three PM fractions sensing (or other measured values), this is even better now - >3 charts would be problematic one under the other. This also takes care of the current problem of the charts not being aligned time-wise (if some readings are missing from one chart or another).

While we are at it, we may try to combine all PM y axes into one, while having separate temperature and rel. humidity axes on their own. All dust-related measurements are called started with "pm...".
