### ISSUE TITLE
Update to ruby 2.3 and latest rails 4.2.x

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#5]
Can I update source to latest ruby and rails? The reason is that I don't have ruby 2.2.0 installed on my machine... What is more ruby 2.3.0 according to some tests (e.g. https://twitter.com/brakeman/status/681564205904953344) is faster.

**Comment by Nuanda** [comment]
Sure.

Dnia 31 grudnia 2015 11:31:21 CET, Marek Kasztelnik <notifications@github.com> napisał(a):
