### ISSUE TITLE
Heatmap - last reading is used as current regardless how old it is

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#55]
Previous heatmap code was strict with date intervals while the current version tends to use a reading that is, for instance, 4 iterations old, as iteration 3, 2, and 1 reading as well (provided it is a last reading).

What is more, I suspect (I didn't tested that particular case) that, with some sensors having newer readings for iteration 3, the iteration 4 readings and iteration 3 readings get mixed together as iteration 3 heatmap data.

I'd like to ask to correct this behavior to have a strict semantics of "last reading in given interval of time". Again, disregard readings with no location. If no readings for a given interval are present, return no reading and display no reading.

**Comment by mkasztelnik** [comment]
Yeach you are right, `from` value is missing. I will fix it.
