### ISSUE TITLE
Mobile - refactor charts for small devices used vertically

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#64]
For instance - phones with 480 px in width. Maybe show shorter series and exclude any non-pm measurements?

**Comment by Nuanda** [comment]
@mkasztelnik This is the task I was talking about. When using small displays, like phones, vertically, the chart is not very legible.

I was thinking to, when detected a smaller screen (width) to display a set of larger numbers for all _last_ measurement readings, above the chart, and then the chart, but much shorter - either with less readings (like, for instance, the last 10) or, which is trickier (and perhaps not needed) some average values.

What do you think?

**Comment by mkasztelnik** [comment]
Are the number of readings the main problem here? Highcharts are quite good for showing huge number of data even in shall chart. To gain more space we can e.g. turn off y axis and have popup show while clicking on concrete chart point. 

Right now chart is no scaled properly on small screen (tested on 384x567)
