### ISSUE TITLE
API - add possibility to set day/hour range (from DD:HH to DD:HH) for CSV download

### ISSUE THREAD

**Issue by Nuanda** [Nuanda/smogmapper#70]
Requested by the sensor designers.

**Comment by Nuanda** [comment]
@mkasztelnik Marek, would you consider implementing that one? By the Download CSV button we need  two smart FROM/TO optional forms (days and hours). Then, the download server action should cut the resulting CSV to the specified time range.

**Comment by mkasztelnik** [comment]
It should allow to download values in defined period for all sensors or for the concrete sensor while modal with sensor chart is shown?

**Comment by Nuanda** [comment]
For that one chosen sensor.
