### ISSUE TITLE
Add possibility to select which reference readings should be shown

### ISSUE THREAD

**Issue by mkasztelnik** [Nuanda/smogmapper#76]
Right now all reference readings are shown, next you can turn it off using chart legend. It is a lot of clicking if you want to compare sensor readings into nearest reference sensor. 

It would be nice to have possibility to select which reference readings to show. To do this e.g. [select 2](https://select2.github.io/examples.html#tags) can be used.

**Comment by Nuanda** [comment]
Actually, my plan is to have the nearest ref station shown and the others disabled. For that, however, I need js-side geo-distance computation ;).

**Comment by Nuanda** [comment]
Done.
